#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 10 16:22:15 2021

@author: canbeyz
"""

import yfinance
#yfinance api is slow to obtain real time data, recommend webpage crawler
import pandas as pd
import datetime


Stock = ['AAPL','SQ','MMM']
#Example Stocks

def rt_price(stock_code):
    stock = yfinance.Ticker(stock_code)
    price = stock.info['currentPrice']
    minus = price - stock.info['previousClose']
    percentchange = minus/stock.info['previousClose']
    change = str(minus)+'('+str(percentchange)+')'
    return price,change

while(True):
    info =[]
    col =[]
    time_stamp = datetime.datetime.now()-datetime.timedelta(hours=13)
    time_stamp=time_stamp.strftime('%Y-%m-%d %h:%M:%S')
    for stock_code in Stock:
        price= rt_price(stock_code)[0]
        change = rt_price(stock_code)[1]
        info.append(price)
        info.extend(change)
    col =[time_stamp]
    col.extend(info)
    df = pd.DataFrame(col)
    df = df.T
    df.to_csv(str('stockdata.csv'),mode ='a', header=False)
    print(col)
    
